### ISSUE TITLE
CS Source compatibility 

### ISSUE THREAD

**Issue by Astro6y** [Rahmid93421/cs1-6-udp-proxy-forwarder#1]
How can I make it work on cs source ?

**Comment by Rahmid93421** [comment]
Hi there, 

I tested the program and it seems that it works with CSS too. To make it work you should to update the game server IP and port to which you want to forward your players. That can be found at the lines 77 and 78 in the source file:


        fwdserver.sin_family = AF_INET;

        if(currip > ips_len-1) currip = 0;
        if(currport > port_len-1) currport = 0;

        fwdip = inet_addr(ips[currip++]);
        fwdport = port[currport++];
        
        fwdserver.sin_addr.s_addr = inet_addr("redirect-server-ip");
        fwdserver.sin_port = htons(redirect-server-port);

        tv.tv_sec = 5.0;    // timeout for recvfrom from ThreadForClient function
        tv.tv_usec = 0;


Where you change "redirect-server-ip" with your server Ip and the redirect-server-port with the server port. Also, I noticed that the info query is different from CS 1.6, so you should be commenting or removing the following code (it can be found inside 'ThreadForClient' method):


    while(1)
    {
        if((clients[id].bufferlen = recvfrom(clients[id].sock, clients[id].buffer, sizeof(clients[id].buffer), 0, (struct sockaddr *)&clients[id].fwdserver, &clients[id].fwdserver_len)))
        {
            
            if(clients[id].bufferlen == -1) 
            {
                clients[id].client.sin_addr.s_addr = 1;
                clients[id].client.sin_port = 1;
                break;
            }

            /*if(clients[id].buffer[0] == 0xFF && clients[id].buffer[1] == 0xFF && clients[id].buffer[2] == 0xFF && clients[id].buffer[3] == 0xFF && clients[id].buffer[4] == 'I')
            {
                clients[id].HostnameChange(clients[id].buffer[4]);
            }
            else
            {
                if(clients[id].buffer[0] == 0xFF && clients[id].buffer[1] == 0xFF && clients[id].buffer[2] == 0xFF && clients[id].buffer[3] == 0xFF && clients[id].buffer[4] == 'm')
                {
                    clients[id].HostnameChange(clients[id].buffer[4]);
                }
            }
            if(clients[id].buffer[0] == 0xFF && clients[id].buffer[1] == 0xFF && clients[id].buffer[2] == 0xFF && clients[id].buffer[3] == 0xFF && clients[id].buffer[4] == 'D')
            {
                clients[id].PlayersInfo();
            }*/
            
            sendto(serversock, clients[id].buffer, clients[id].bufferlen, 0, (struct sockaddr *)&clients[id].client, clients[id].fwdserver_len);
        }
    }
`

**Comment by Astro6y** [comment]
Thank you for the fast & detailed reply! I'll try to adjust the code & tell you.
